### PR TITLE
Hudl meetup and Bugfix merged for dropofwill

### PR DESCRIPTION
**Pull request by dropofwill**

### CODE REVIEW

**Comment by ryansb** [comment]
:+1: Looks good to me. CC @decause

**Comment by decause** [comment]
:hamburger: 

@dropofwill change <code>bugfixupstream</code> to <code>upstream1</code>.

Fix and I'll merge :wrench:

**Comment by dropofwill** [comment]
@decause updated it

**Comment by liam-middlebrook** [comment]
lgtm :+1:

**Pull request merged**
