### PR TITLE
Adding fork me on GitHub Banner

### PR DESCRIPTION
**Pull request by kocsenc**
With the recent addition of the `Fork me on Github` link I thought it might be cool to add the classic banner!

### CODE REVIEW

**Comment by decause** [comment]
@kocsenc 

I like this idea, as it is classic. How does it look on Mobile?

Also, be sure to <code>git pull</code> and merge changes from upstream so I can auto-merge if appropriate.

**Comment by kocsenc** [comment]
When resizing, it just becomes a link at the top of the page with the same styling. So it does have responsive design. 

Pulling for update.
Kocse

**Comment by ryansb** [comment]
As-is this will create a pretty large merge bubble. Please rebase this branch and open a new PR.

**Comment by decause** [comment]
@kocsenc and @ryansb did we ever sort this out?

**Comment by ryansb** [comment]
Nope, still an enormous merge bubble.

**Comment by decause** [comment]
since hflossk is deprecated, I think I'm going to have to close this one. Thanks for input @kocsenc

**Pull request closed without merging**
