### PR TITLE
Added commarch stuff to yaml

### PR DESCRIPTION
**Pull request by Nolski**

### CODE REVIEW

**Comment by Qalthos** [comment]
Check out the conversation in #147, the fix to lectures.mak is no longer necessary and will cause a merge conflict.

After working with @rxg1565 on this, I think your best option is probably to pull from @decause again, and you should get a merge conflict as lectures.mak no longer exists, just keep the deleted file, then push again to your fork to update this pull request.

Stop by the FOSSBox if you need help with this.

**Comment by decause** [comment]
:question: to the lectures.mak commit
:+1: to the .yaml commits

@mpn3712 reconcile this with me during class time, or in the FOSSBox

**Comment by Qalthos** [comment]
I'm not sure what you did to make the commit 'update', but you solved the merge conflict in the wrong way.

`git rm templates/lectures.mak` from the root of the repository then push & try again.

If you have trouble with this, or it doesn't seem to do the right thing, or you're completely confused, ask myself or @decause for help

**Comment by decause** [comment]
@mpn3712 do what @Qalthos said above, and I'll merge

**Comment by decause** [comment]
:tophat:

**Pull request merged**
