### PR TITLE
Danny Nguyen LitReview

### PR DESCRIPTION
**Pull request by dxn7335**
LitReview 1 hw added to yaml file

### CODE REVIEW

**Comment by ryansb** [comment]
The build result: `found character '\t' that cannot start any token`

Please remove the tab and indent your homework w/ two spaces instead.

**Comment by dxn7335** [comment]
I have just fixed the yaml file to remove the tab and include 2 spaces

**Comment by ryansb** [comment]
:+1: cc: @decause

**Comment by decause** [comment]
@dxn7335 remove the <code>hw:</code> and dedent <code>litreview1</code>

Fix and I'll merge :wrench:

**Pull request merged**
