### PR TITLE
Added Libravatar support; Made URLS backwards compatible

### PR DESCRIPTION
**Pull request by liam-middlebrook**
Fixed issue #370

### CODE REVIEW

**Comment by ralphbean** [comment]
Is this possible?  We had trouble with this kind of thing [here](https://github.com/fedora-infra/tahrir/pull/209) and [here](https://bugs.launchpad.net/libravatar/+bug/1219117).

I'll be glad to know if you have a way to make it work.  :)

**Comment by liam-middlebrook** [comment]
@ralphbean I've tested this fix on my local box. After a quick search through libravatar's API I found out that you are able to query one of their URLS and then add an optional HTTP GET parameter for a fallback URL. 

It follows this format:
`"https://seccdn.libravatar.org/avatar/" + id +"?d=https://secure.gravatar.com/avatar/" + id`

**Comment by ralphbean** [comment]
Ah, I see.  I think we were trying to add one more link to the chain and failing at that.  Something like this:

``` python
>>> "https://seccdn.libravatar.org/avatar/" + id  + "?d=" + encoded(
...     "https://secure.gravatar.com/avatar/" + id + "?d=" + encoded(
...         "https://fan.cy/default-image.png"))
```

**Comment by liam-middlebrook** [comment]
In commit https://github.com/liam-middlebrook/hflossk/commit/897c2d8e128dc6ec59e3c3a633df6f4e78b5749c I made the site's URL structure backwards compatible. This fixes issue #372 which was caused my @mansam's commit https://github.com/decause/hflossk/commit/efb8198fc9371a0919fba001f345bda620d47468

@decause  Now all the links to /hw and /quiz should work again! Fixing #372

**Pull request merged**
