### PR TITLE
Added more Mac IRC clients

### PR DESCRIPTION
**Pull request by kocsenc**
Added IRC clients for Mac OS X.

### CODE REVIEW

**Comment by kocsenc** [comment]
Fixing Formatting...

**Comment by ryansb** [comment]
:-1: You actually updated the format _from_ 2 space tabs _to_ hard tabs.

**Comment by kocsenc** [comment]
I can switch it back, most of the file was actually hard tabbed, which is why I did that.

Also clarification where '2space tabs' means the hard tabs are 2 spaces wide.

**Comment by ryansb** [comment]
Everywhere else we use 2 space (as in "the space character") tabs. Can you please stick to that?

**Comment by kocsenc** [comment]
As a word of caution, many static files have a mix between soft & hard tabs. I only changed it because most of the tabs in this file were hard tabs. Thanks for letting me know!

**Comment by ryansb** [comment]
I'm very aware, it's...yeah, let's just try to keep as consistent as possible going forward. Unfortunately a mass whitespace fix loses a lot of git blame history. :(

**Comment by ryansb** [comment]
Looks great to me. Also :+1: for adding Textual. cc @decause for merge.

**Comment by decause** [comment]
Nice work @kocsenc!

:100:

**Pull request merged**
