### PR TITLE
Fix RSS Feed link

### PR DESCRIPTION
**Pull request by MrNex**
RSS feed seemed to not be working. Removed "en" prefix in hopes it will address the issue.

### CODE REVIEW

**Comment by ryansb** [comment]
Have you tested this change to see if it fixes the problem?

**Comment by MrNex** [comment]
I have not, however I viewed kangarueben's yaml, who also has a ​wordpress,
and that on first glance seemed to be the only difference between our RSS
feed keys. His is working fine, mine is not.
I don't have time at the moment but since I'm assuming the github
description has testing instructions, when I do have a minute (could need
to wait until the weekend) I can try testing it.
However, navigating to both en.nexleveldevelopment.wordpress.com/feed and
nexleveldevelopment.wordpress.com/feed yields the exact same result. So
unless it's a yaml parsing related issue this really shouldn't change
anything- I'm just not sure what else to try.

**Comment by ryansb** [comment]
It is generally advisable to test your changes before filing a pull request. There are testing instructions, but I'll repeat them here. First, run these commands.

```
pip install -r requirements.txt
python setup.py develop
python app.py
```

Then go to http://localhost:5000/ in your browser to check the results.

**Comment by MrNex** [comment]
Sounds good, thank you for your assistance, I will run a test as soon as I
can and resolve the issue.

**Pull request merged**
