### PR TITLE
Cleaning up some logic

### PR DESCRIPTION
**Pull request by msoucy**
Updated a docstring, made some cleaner style choices, fixed some person lookup logic.

### CODE REVIEW

**Comment by liam-middlebrook** [comment]
lgtm :thumbsup:

**Comment by ryansb** [comment]
Can you maybe write a test to verify your changes? I know there wasn't one before, but it'd be great to improve our test coverage.

**Comment by msoucy** [comment]
The nature of this section of code means that tests would rely on specific users being lookup-able...so, tests are POSSIBLE, though I wouldn't quite say practical.

**Comment by msoucy** [comment]
Aaaaaaaand wrong button.

**Comment by ryansb** [comment]
:+1:

**Comment by decause** [comment]
/me merges patch and opens a new tab to: http://butt.holdings/

**Pull request merged**
