### PR TITLE
Added class sugestion for 11/27

### PR DESCRIPTION
**Pull request by Nolski**

### CODE REVIEW

**Comment by f4ngy** [comment]
Some of us have zero experience with vim..will this topic cover the basics as well or will it go over some of our heads?

**Comment by Nolski** [comment]
@decause ping
@lle6138 I think it will be pretty intro. I don't have a ton of experience.

**Comment by h2g2guy** [comment]
I can give input on/help with this presentation.  3-ish years of experience with vim, been playing with my .vimrc and plugins a lot lately.  It's not a lot, but it's something ;-)

**Comment by Nolski** [comment]
@h2g2guy That would be pretty cool! I would love to see if there is a way to enable some form of code completion or linting for python/javascript.

**Comment by h2g2guy** [comment]
I don't have any personal experience with that area, but this plugin might help for python:  https://github.com/klen/python-mode

For syntax checking in general, Syntastic is a rather popular option:  https://github.com/scrooloose/syntastic 

I personally like to keep vim set up as more of a versatile, language-agnostic code editor than a full blown IDE --especially as I continue to learn the advanced functionality that's already built in -- so I don't really care for these kinds of plugins.  But there are certainly plenty of them out there if you want that sort of functionality!

Is this the sort of thing you were thinking about covering during class?

**Comment by Nolski** [comment]
Maybe for part of it. I'm still pretty new to vim so I think learning a lot of the commands in command mode (dd, p, all of the different ways to get into insert mode, etc.) would be the focus.

**Comment by h2g2guy** [comment]
Agreed.  If I might make a further suggestion, I think the different motion operators (w, e, b, f, ^, $, G, /, etc.) combined with text manipulation commands are a really good thing to at least demonstrate to users who are just getting into vim.  Vim is HARD to get started with.  But seeing the power behind the various commands you can wield -- and see how vim's editing paradigm actually works -- is I think one of the best ways to get excited about it.

**Comment by decause** [comment]
@Nolski this would be great, but obv class was cancelled. Put it on the calendar for another day ;)

**Pull request closed without merging**
