### PR TITLE
Added the Lit Review

### PR DESCRIPTION
**Pull request by rxg1565**
See above

### CODE REVIEW

**Comment by decause** [comment]
Just change "Lit Review" to "litreview1" and I'll merge.

**Comment by decause** [comment]
@rxg1565 see above comment

**Comment by decause** [comment]
I am not sure what is going on here... I'm almost positive that I made those commits earlier today, but here they are showing up as being done by @rxg1565 ... perhaps @Qalthos could explain what is the haps here?

Today in class, IIRC, @rxg1565 edited the people.yaml file by mistake, so we wanted to revert it back to before he edited it.

we did something like:
$ git checkout eee547c -- scripts/people/people.yaml
$ git commit
$ git push

unless I am confusing @rxg1565 with someone else, this is how it went down. Thoughts?
@ralphbean feel free to chime in also :P

**Comment by decause** [comment]
I may have the wrong hash in there, but you get the drill... also, github auto-recognizes hashes in comments!?!
:octocat: :metal:

**Comment by decause** [comment]
@rxg1565 There is much shenanigans at play here... we should sit down soon in the FOSSBox and sort out exactly what is going on with your repo. Perhaps doing a fresh clone, and then re-editing your .yaml file would be advisable?

**Comment by rxg1565** [comment]
@decause I sent an email explaining my delay on seeing this problem. 

Here is what I think may have happened: Last wednesday during class we pulled from the cloud to my local machine and then updated my GitHub repo so my fork matched the files you had in the cloud. I believe my repo in GitHub made the mistake that I had updated those files instead of me just trying to update my own repo, so when I sent my pull request for the quiz, it sent it for everything I had just updated (because technically it was new stuff that had changed in my repo). I'm not exactly sure how to fix that however. But I'm more than willing to sit down and figure it out

**Comment by rxg1565** [comment]
I tried to reclone it but Git says that hflossk already exists

**Comment by decause** [comment]
@rxg1565 when you are healthy again, please come to the FOSSBox and sort this out. Send me an email ASAP and let me know when you're coming in.

**Comment by decause** [comment]
@rxg1565 finally came in and got his help. This PR is moot.

**Pull request closed without merging**
