### PR TITLE
Update Waterseas.yaml

### PR DESCRIPTION
**Pull request by Waterseas**
QUiz added

### CODE REVIEW

**Comment by decause** [comment]
Close. Be sure to align the quiz link with the other items in the list (.yaml is whitespace sensitive)

Also, where is your litreview1 link???

:grey_question:

**Comment by decause** [comment]
Fix the whitespace issue, and your litreview1 link, and I'll merge.

**Comment by Waterseas** [comment]
Should be fixed now
- Waterseas

Date: Wed, 11 Sep 2013 17:42:00 -0700

**Comment by decause** [comment]
It's almost fixed... sort of...

1) Be sure the quiz entry is aligned with the other entries in the list. Are you using a monospaced font in your editor?
2) Be sure the name of your quiz entry is "quiz1" as discussed during class, and in the instructions
3) Where is your litreview1 link :interrobang:

**Comment by decause** [comment]
@Waterseas this is still not fixed. It has been 15 days. Fixmeplz :wrench:

**Comment by decause** [comment]
looks like I already merged your quiz

**Pull request closed without merging**
