### PR TITLE
Added VidReview2 and Updated snapschott.yaml

### PR DESCRIPTION
**Pull request by snapschott**

### CODE REVIEW

**Comment by decause** [comment]
@snapschott be sure to <code>git pull</code> from upstream and merge your changes.

Fix and I'll merge :wrench:

**Comment by decause** [comment]
@snapschott please see above.

**Comment by snapschott** [comment]
@decause Can you let me know if it works now plz?

**Comment by liam-middlebrook** [comment]
lgtm :+1:

**Comment by decause** [comment]
:snail:

**Pull request merged**
