### PR TITLE
Added Why Dotfiles Are Meant to Be Forked blogpost link

### PR DESCRIPTION
**Pull request by liam-middlebrook**

### CODE REVIEW

**Comment by ryansb** [comment]
I'd argue that this shouldn't be included because it is
- a blog post, not a book
- an external link, which we try to minimize for resource content

**Comment by decause** [comment]
We'll have to come up with a more clever way of utilizing mako templates for things like this. The /static directory assumes that books and other resources are already in a digestible format (i.e. .pdf, and/or .txt, etc...) so the /videos path was kind of a hack, and this continues down that hackish path.

I can imagine a couple of solutions:
- create an oer.yaml file that is passed to the resources.mak template
- Add a field to the site.yaml file to be passed into resources.mak (preferable?)
- <strike>hardcoded into the resources.mak template</strike>

thoughts @ryansb and/or @ralphbean?

**Comment by liam-middlebrook** [comment]
I think that creating an oer.yaml file that is parsed by resources.mak makes the most sense.

**Comment by liam-middlebrook** [comment]
- passed into

I can't edit from my phone

**Comment by ryansb** [comment]
I'll look into this tonight.

**Comment by liam-middlebrook** [comment]
I'm going to close this for now. Sometime in the next few days (before the HackFest) I'll work on making the resource section support links from a yaml as well as files.

**Pull request closed without merging**
