### PR TITLE
Kocsen first flight

### PR DESCRIPTION
**Pull request by kocsenc**
Created my Yaml file!

### CODE REVIEW

**Comment by ryansb** [comment]
Your yaml file is missing the "forges" and "feeds" tags (that's why the TravisCI build is failing). See https://github.com/decause/hflossk/blob/master/scripts/people/2014/fall/testfall2014.yaml as an example.

**Comment by kocsenc** [comment]
Thanks Ryan, I didn't have them at the time. They should be up. I also have to ask @decause about forges during class.

**Comment by ryansb** [comment]
Looks good to me. CC @decause for merge

**Comment by decause** [comment]
:dog2:

**Pull request merged**
