### PR TITLE
Bugfix

### PR DESCRIPTION
**Pull request by Honeybunch**

### CODE REVIEW

**Comment by decause** [comment]
@Honeybunch before pushing any changes to your repository, make sure that you git pull from decause/hflossk so that you have the latest bits, and then push to your repo (it will automatically update your pull request.)

**Comment by Honeybunch** [comment]
Ok Everything should be up to date now

**Comment by Honeybunch** [comment]
@decause everything should be up to date and my commarch report link is in there too. Is there anything I have to do to get rid of the merge conflicts?

**Comment by decause** [comment]
/me will just merge this by hand... this time... but next time you gotta be sure to <code>git pull</code> once in a while, savvy?

**Pull request merged**
