### PR TITLE
added yaml file to master branch

### PR DESCRIPTION
**Pull request by tconroy**
accidentally sent it to dev branch before, woops. :)

### CODE REVIEW

**Comment by ryansb** [comment]
:+1: cc @decause

**Comment by tconroy** [comment]
cc @decause :  my yaml still needs to be merged into master. Just pushed up a commit for my litreview1 link. Thanks!

**Comment by decause** [comment]
@tconroy remove the <code>----</code> and <code>hw:</code> and then dedent <code>literview1</code>

Fix and I'll merge :wrench:

**Comment by tconroy** [comment]
@decause : fix pushed :+1:

**Comment by decause** [comment]
@tconroy the quotes <code>"</code>

Fix and I'll merge :wrench:

**Comment by tconroy** [comment]
@decause : gah! fixed. :)

**Comment by decause** [comment]
:cake:

**Pull request merged**
