### PR TITLE
added quiz to yaml

### PR DESCRIPTION
**Pull request by nekocoder**

### CODE REVIEW

**Comment by decause** [comment]
@nekocoder be sure to remove that extra space in your last entry `quiz 1` should be `quiz1`.

:wrench: fix and I'll merge.

**Comment by nekocoder** [comment]
is this better?

**Comment by decause** [comment]
@nekocoder that is better, but now you need a space after the name of the field... `quiz1:`

:wrench: fix and I'll merge

**Comment by nekocoder** [comment]
Should be better now (I hope)

**Comment by decause** [comment]
:ship:

**Pull request merged**
