### PR TITLE
Update snapschott.yaml

### PR DESCRIPTION
**Pull request by snapschott**
Added Quiz

### CODE REVIEW

**Comment by decause** [comment]
@snapschott be sure to <code>git pull</code> and merge upstream. Cannot auto-merge.

**Comment by ryansb** [comment]
Grumble grumble merge bubbles.

**Comment by decause** [comment]
@ryansb :heart_eyes_cat:

**Comment by ryansb** [comment]
@decause I have no idea what that emoji is supposed to mean. 

@snapschott please try this instead.

```
git fetch https://github.com/decause/hflossk.git HEAD:decauseMaster
git checkout decauseMaster # get the master branch from Decause's repo
git checkout master -- scripts/people/2014/fall/snapschott.yaml # get the changes you have in this PR
git commit -m 'Update snapschott.yaml' # commit those changes
git push -f origin decauseMaster:master # overwrite your master with your updated changes
```

Then you will be able to open a new PR that will merge correctly.

**Comment by decause** [comment]
@snapschott you got this?

**Comment by snapschott** [comment]
Yeah, I'll fix it

On Tue, Dec 16, 2014 at 1:37 PM, Remy DeCausemaker <notifications@github.com

**Comment by snapschott** [comment]
Okay I made a new pull request that hopefully fixed the quiz2 merge problem
and added the finalpreso

**Comment by ryansb** [comment]
Looks great, I'm going to close this PR then.

**Pull request closed without merging**
