### PR TITLE
Added bugfix

### PR DESCRIPTION
**Pull request by Berulacks**

### CODE REVIEW

**Comment by decause** [comment]
@ralphbean code review plz :)

**Comment by ralphbean** [comment]
Looks good to me.

**Comment by ralphbean** [comment]
:+1:!

**Comment by Xethik** [comment]
I was just writing this up myself, beat me to it.

**Comment by mansam** [comment]
Hey @Berulacks, it looks like your repository was very out of date when you made this pull request. I recommend closing this request, doing a git pull from @decause's master so that the only thing that's different is your change to your yaml file, and then making a new pull request.

**Pull request closed without merging**
