### PR TITLE
Added meetup  1 @RocPy

### PR DESCRIPTION
**Pull request by dxn7335**
For some reason there seems to be a change shown on line 938 of templates/syllabus.mak. Its on the last line and seems to be a difference of spacing but I dont see any difference between the original file and the one on my own local file. I don't know if this will effect anything.

### CODE REVIEW

**Comment by decause** [comment]
@dxn7335 before pushing any changes to your repository, make sure that you <code>git pull</code> from decause/hflossk so that you have the latest bits, and then push to your repo (it will automatically update your pull request.)

**Comment by decause** [comment]
@dxn7335 you should <code>git checkout syllabus.mak</code> to revert the changes you've made to it, and then push to your repo again.

Fix and I'll merge :wrench:

**Comment by dxn7335** [comment]
I have just reverted the change from syllabus.mak

**Comment by decause** [comment]
@dxn7335 good work.

:smiley:

**Pull request merged**
