### PR TITLE
Teamprop1 and bugfix added

### PR DESCRIPTION
**Pull request by Lynxfive**

### CODE REVIEW

**Comment by decause** [comment]
@Lynxfive before pushing any changes to your repository, make sure that you git pull from decause/hflossk so that you have the latest bits, and then push to your repo (it will automatically update your pull request.)

**Comment by decause** [comment]
@Lynxfive before pushing any changes to your repository, make sure that you git pull from decause/hflossk so that you have the latest bits, and then push to your repo (it will automatically update your pull request.)

**Comment by decause** [comment]
@Lynxfive you have merge conflicts. If you need help, stop into IRC, or come see folks in the FOSSBox.

**Comment by Lynxfive** [comment]
@decause Is this all fixed? I haven't been able to send a pull request for a while, I think it is because of this stuff.

**Comment by decause** [comment]
:tiger2:

**Pull request merged**
