### PR TITLE
Added vidreview2 and meetup3 and removed meetup 2 from Faokryn.yaml

### PR DESCRIPTION
**Pull request by faokryn**

### CODE REVIEW

**Comment by ryansb** [comment]
Please rebase these changes, otherwise you'll create a large merge bubble. :-1:

**Comment by faokryn** [comment]
@ryansb wat?

**Comment by ryansb** [comment]
You can fetch decause's repo and rebase your changes like this

```
$ git remote add upstream https://github.com/decause/hflossk
$ git fetch upstream
```

Now that you have the changes, check out the commit where you changed your yaml and make a new branch.

```
$ git checkout upstream/master
$ git checkout -b newYaml
```

Now grab your YAML changes.

```
$ git checkout master -- scripts/people/2014/fall/Faokryn.yaml
$ git add scripts/people/2014/fall/Faokryn.yaml
$ git commit -m "Add vidreview, hackathons, and hudl talk"
```

And now you're ready to push those changes to your github repo

```
$ git push --force origin newYaml:master 
```

Now you're ready to make a new pull request that won't make a huge merge bubble.

**Comment by faokryn** [comment]
@ryansb Please explain to me
1.  What this does.
2.  Why it is necessary ("--force" makes me nervous)
3.  What caused the error in the first place (so I can avoid it in the future)
Thank you :]

**Comment by ryansb** [comment]
It checks out decause's upstream repository's master branch, then checks out your changes (to your YAML file, in this case) onto it. Once your YAML is checked out, you commit it again and then `push --force` to overwrite your current master (the one with the merge we're avoiding) with the new one (the one with only the YAML changes.

The reason this happened is because you failed to keep your fork up to date by fetching the upstream (decause's) master branch and making your changes atop that. In the future, if you make sure your repo is up to date with upstream before making changes this won't happen.

**Comment by faokryn** [comment]
@ryansb OK, followup questions.  If I understand correctly, the reason for doing this is to get rid of the "Merge branch 'master' of https://github.com/decause/hflossk" commit (f3822a06f4f30ba1fd6cefdf78d1d65c15b99f3b).  How is this different from the commits 26016c05df224f00e8b39f260e109f8acf5273cc and aba31717382d2ffb5e07fe4a9c188f712ea5f342 in pull request #525 and the commit b898aeef1890fad32ade92e12e59d5ce9164dfbd in pull request #564?

Also, and again if I understand correctly, won't this overwrite the commits in this pull request and get rid of the pull request?  Since @decause uses the times that pull requests were issued to determine when an assignment was turned in, could doing this cause problems?

**Comment by ryansb** [comment]
Correct. This pull request will be closed (I don't recall if github auto-closes them or you need to do it manually) and you'll open a new one. You can refer to this one in your new request by saying something like `Reopen #606`.

**Comment by decause** [comment]
:twisted_rightwards_arrows:  :speech_balloon:

**Comment by ryansb** [comment]
What do these emoticons even mean?

**Pull request merged**
