### PR TITLE
Fixed width aesthetics

### PR DESCRIPTION
**Pull request by taters343**
I made it so that the navbar at the top doesn't shrink to the collapsable version until it actually runs out of space. I also fixed the problem that would cause the nav bar to cut into the content of the page at certain widths.

Fixed issue #98

### CODE REVIEW

**Comment by taters343** [comment]
Also added the assignment to my yaml file.

**Comment by decause** [comment]
Excellent! Can you confirm that you've tested this commit, and that things don't break?

**Comment by taters343** [comment]
I tested it on Windows with Chrome and Firefox and it worked. Do you want me to test it on Fedora and Android as well?

Edit: Actually, I have no idea how I would test it on Android.

**Comment by decause** [comment]
:horse_racing:

**Pull request merged**
